---
title: "HW 1 Data Science"
author: "Victoria Mello vsm2118"
date: "September 19, 2023"
output: github_document
---
# Promblem 1

```{r}
# Load the moderndive package
library(moderndive)

# Load the early_january_weather dataset
data("early_january_weather")
```

The `early_january_weather` dataset contains information about...

```{r}
# Access dataset help file
?early_january_weather
```

```{r}
# Variables in the dataset
names(early_january_weather)

# Size of the dataset (number of rows and columns)
nrow(early_january_weather)  # Number of rows
ncol(early_january_weather)  # Number of columns

# Mean temperature
mean_temp <- mean(early_january_weather$temp)
mean_temp
```

```{r}
library(ggplot2)

# Create the scatterplot
scatter_plot <- ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) +
  geom_point() +
  labs(x = "Time Hour", y = "Temperature", title = "Scatterplot of Temperature vs. Time Hour") +
  theme_minimal()

# Display the scatterplot
print(scatter_plot)
```